In [1]:
print("hello world")

hello world

In [ ]:
mongodb+srv://tajuarakash:tajuarakash@cluster0.pr8dot3.mongodb.net/?appName=Cluster0

In [2]:
import pandas as pd

In [4]:
%pwd

'c:\\Users\\User\\Desktop\\End_to_end_us_visa_project\\End-to-End-Machine-Learning-Project\\notebook'

In [7]:
df = pd.read_csv("Visadataset.csv")
df.head()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified

In [8]:
data = df.to_dict(orient='records')

In [12]:
DB_NAME = 'US_VISA'
COLLECTION_NAME = 'visa_data'
CONNECTION_URL = "mongodb+srv://tajuarakash:tajuarakash@cluster0.pr8dot3.mongodb.net/?appName=Cluster0"

In [14]:
import pymongo

client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

In [15]:
rec = collection.insert_many(data)

# GET Data

In [16]:
records = collection.find()
for record in records:
    print(record)

{'_id': ObjectId('6a00488691d8302b348aa66c'), 'case_id': 'EZYV01', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 14513, 'yr_of_estab': 2007, 'region_of_employment': 'West', 'prevailing_wage': 592.2029, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied'}
{'_id': ObjectId('6a00488691d8302b348aa66d'), 'case_id': 'EZYV02', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2412, 'yr_of_estab': 2002, 'region_of_employment': 'Northeast', 'prevailing_wage': 83425.65, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa66e'), 'case_id': 'EZYV03', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 44444, 'yr_of_estab': 2008, 'region_of_employment': 'West', 'prevailing_wage': 122996.86, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
{'_id': ObjectId('6a00488691d8302b348aa66f'), 'case_id': 'EZYV04', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 98, 'yr_of_estab': 1897, 'region_of_employment': 'West', 'prevailing_wage': 83434.03, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
{'_id': ObjectId('6a00488691d8302b348aa670'), 'case_id': 'EZYV05', 'continent': 'Africa', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1082, 'yr_of_estab': 2005, 'region_of_employment': 'South', 'prevailing_wage': 149907.39, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa671'), 'case_id': 'EZYV06', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2339, 'yr_of_estab': 2012, 'region_of_employment': 'South', 'prevailing_wage': 78252.14, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa672'), 'case_id': 'EZYV07', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 4985, 'yr_of_estab': 1994, 'region_of_employment': 'South', 'prevailing_wage': 53635.39, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa673'), 'case_id': 'EZYV08', 'continent': 'North America', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3035, 'yr_of_estab': 1924, 'region_of_employment': 'West', 'prevailing_wage': 418.2298, 'unit_of_wage': 'Hour', 'full_time_position': 'Y', 'case_status': 'Denied'}
{'_id': ObjectId('6a00488691d8302b348aa674'), 'case_id': 'EZYV09', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 4810, 'yr_of_estab': 2012, 'region_of_employment': 'Midwest', 'prevailing_wage': 74362.19, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa675'), 'case_id': 'EZYV10', 'continent': 'Europe', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2251, 'yr_of_estab': 1995, 'region_of_employment': 'South', 'prevailing_wage': 67514.76, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa676'), 'case_id': 'EZYV11', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2465, 'yr_of_estab': 2004, 'region_of_employment': 'Midwest', 'prevailing_wage': 83588.56, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa677'), 'case_id': 'EZYV12', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4069, 'yr_of_estab': 2005, 'region_of_employment': 'Northeast', 'prevailing_wage': 70813.09, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
{'_id': ObjectId('6a00488691d8302b348aa678'), 'case_id': 'EZYV13', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 123876, 'yr_of_estab': 1963, 'region_of_employment': 'Northeast', 'prevailing_wage': 28663.05, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa679'), 'case_id': 'EZYV14', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1652, 'yr_of_estab': 2007, 'region_of_employment': 'Midwest', 'prevailing_wage': 107196.03, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa67a'), 'case_id': 'EZYV15', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 15756, 'yr_of_estab': 2006, 'region_of_employment': 'South', 'prevailing_wage': 220081.73, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa67b'), 'case_id': 'EZYV16', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4897, 'yr_of_estab': 1987, 'region_of_employment': 'West', 'prevailing_wage': 74108.02, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
{'_id': ObjectId('6a00488691d8302b348aa67c'), 'case_id': 'EZYV17', 'continent': 'Europe', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 76638, 'yr_of_estab': 1991, 'region_of_employment': 'Midwest', 'prevailing_wage': 3706.79, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa67d'), 'case_id': 'EZYV18', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2747, 'yr_of_estab': 2001, 'region_of_employment': 'West', 'prevailing_wage': 16132.61, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa67e'), 'case_id': 'EZYV19', 'continent': 'Africa', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 4743, 'yr_of_estab': 2004, 'region_of_employment': 'Midwest', 'prevailing_wage': 150441.13, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa67f'), 'case_id': 'EZYV20', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 843, 'yr_of_estab': 1972, 'region_of_employment': 'Midwest', 'prevailing_wage': 79948.12, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa680'), 'case_id': 'EZYV21', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 880, 'yr_of_estab': 2008, 'region_of_employment': 'West', 'prevailing_wage': 71128.98, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
{'_id': ObjectId('6a00488691d8302b348aa681'), 'case_id': 'EZYV22', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1706, 'yr_of_estab': 2013, 'region_of_employment': 'Midwest', 'prevailing_wage': 137694.98, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa682'), 'case_id': 'EZYV23', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2878, 'yr_of_estab': 1968, 'region_of_employment': 'West', 'prevailing_wage': 45642.39, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa683'), 'case_id': 'EZYV24', 'continent': 'North America', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1517, 'yr_of_estab': 1884, 'region_of_employment': 'Midwest', 'prevailing_wage': 90108.38, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa684'), 'case_id': 'EZYV25', 'continent': 'Europe', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 241, 'yr_of_estab': 1981, 'region_of_employment': 'Midwest', 'prevailing_wage': 71286.04, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa685'), 'case_id': 'EZYV26', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1100, 'yr_of_estab': 1997, 'region_of_employment': 'Midwest', 'prevailing_wage': 99489.65, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa686'), 'case_id': 'EZYV27', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 756, 'yr_of_estab': 1995, 'region_of_employment': 'South', 'prevailing_wage': 86332.95, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa687'), 'case_id': 'EZYV28', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 2889, 'yr_of_estab': 2005, 'region_of_employment': 'South', 'prevailing_wage': 103029.33, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa688'), 'case_id': 'EZYV29', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 18, 'yr_of_estab': 2004, 'region_of_employment': 'Northeast', 'prevailing_wage': 40925.86, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa689'), 'case_id': 'EZYV30', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 758, 'yr_of_estab': 2009, 'region_of_employment': 'Northeast', 'prevailing_wage': 189190.48, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa68a'), 'case_id': 'EZYV31', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1408, 'yr_of_estab': 1998, 'region_of_employment': 'Midwest', 'prevailing_wage': 79594.12, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa68b'), 'case_id': 'EZYV32', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 995, 'yr_of_estab': 1880, 'region_of_employment': 'South', 'prevailing_wage': 135866.13, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa68c'), 'case_id': 'EZYV33', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2415, 'yr_of_estab': 1963, 'region_of_employment': 'Midwest', 'prevailing_wage': 72077.57, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa68d'), 'case_id': 'EZYV34', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 2395, 'yr_of_estab': 2000, 'region_of_employment': 'South', 'prevailing_wage': 81921.18, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa68e'), 'case_id': 'EZYV35', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1809, 'yr_of_estab': 2010, 'region_of_employment': 'South', 'prevailing_wage': 225569.73, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa68f'), 'case_id': 'EZYV36', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 5512, 'yr_of_estab': 2001, 'region_of_employment': 'Northeast', 'prevailing_wage': 92421.92, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
{'_id': ObjectId('6a00488691d8302b348aa690'), 'case_id': 'EZYV37', 'continent': 'Europe', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2520, 'yr_of_estab': 1981, 'region_of_employment': 'West', 'prevailing_wage': 2490.12, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
{'_id': ObjectId('6a00488691d8302b348aa691'), 'case_id': 'EZYV38', 'continent': 'Europe', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 44, 'yr_of_estab': 1965, 'region_of_employment': 'South', 'prevailing_wage': 110817.26, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa692'), 'case_id': 'EZYV39', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'Y', 'no_of_employees': 2206, 'yr_of_estab': 1909, 'region_of_employment': 'Northeast', 'prevailing_wage': 50960.01, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa693'), 'case_id': 'EZYV40', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 3729, 'yr_of_estab': 2007, 'region_of_employment': 'Midwest', 'prevailing_wage': 125336.9, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa694'), 'case_id': 'EZYV41', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3723, 'yr_of_estab': 2011, 'region_of_employment': 'West', 'prevailing_wage': 39633.32, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa695'), 'case_id': 'EZYV42', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 1209, 'yr_of_estab': 1989, 'region_of_employment': 'Northeast', 'prevailing_wage': 156326.33, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa696'), 'case_id': 'EZYV43', 'continent': 'Europe', 'education_of_employee': 'Doctorate', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 19770, 'yr_of_estab': 2005, 'region_of_employment': 'West', 'prevailing_wage': 43630.58, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa697'), 'case_id': 'EZYV44', 'continent': 'North America', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2582, 'yr_of_estab': 1989, 'region_of_employment': 'South', 'prevailing_wage': 54614.42, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa698'), 'case_id': 'EZYV45', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 5407, 'yr_of_estab': 1998, 'region_of_employment': 'West', 'prevailing_wage': 28989.87, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
{'_id': ObjectId('6a00488691d8302b348aa699'), 'case_id': 'EZYV46', 'continent': 'Europe', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 2092, 'yr_of_estab': 1998, 'region_of_employment': 'South', 'prevailing_wage': 22924.91, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa69a'), 'case_id': 'EZYV47', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2623, 'yr_of_estab': 2008, 'region_of_employment': 'South', 'prevailing_wage': 61567.75, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa69b'), 'case_id': 'EZYV48', 'continent': 'Asia', 'education_of_employee': 'High School', 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 226, 'yr_of_estab': 1991, 'region_of_employment': 'Midwest', 'prevailing_wage': 156251.17, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa69c'), 'case_id': 'EZYV49', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 2405, 'yr_of_estab': 1933, 'region_of_employment': 'South', 'prevailing_wage': 86022.02, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa69d'), 'case_id': 'EZYV50', 'continent': 'Asia', 'education_of_employee': 'Doctorate', 'has_job_experience': 'N', 'requires_job_training': 'Y', 'no_of_employees': 2171, 'yr_of_estab': 1960, 'region_of_employment': 'Northeast', 'prevailing_wage': 49565.37, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Denied'}
{'_id': ObjectId('6a00488691d8302b348aa69e'), 'case_id': 'EZYV51', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 746, 'yr_of_estab': 1991, 'region_of_employment': 'Midwest', 'prevailing_wage': 66191.41, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa69f'), 'case_id': 'EZYV52', 'continent': 'Asia', 'education_of_employee': "Master's", 'has_job_experience': 'Y', 'requires_job_training': 'N', 'no_of_employees': 3129, 'yr_of_estab': 2003, 'region_of_employment': 'Midwest', 'prevailing_wage': 95623.2, 'unit_of_wage': 'Year', 'full_time_position': 'N', 'case_status': 'Certified'}
{'_id': ObjectId('6a00488691d8302b348aa6a0'), 'case_id': 'EZYV53', 'continent': 'Asia', 'education_of_employee': "Bachelor's", 'has_job_experience': 'N', 'requires_job_training': 'N', 'no_of_employees': 1647, 'yr_of_estab': 1998, 'region_of_employment': 'Midwest', 'prevailing_wage': 115014.05, 'unit_of_wage': 'Year', 'full_time_position': 'Y', 'case_status': 'Certified'}

In [20]:
df = pd.DataFrame(list(collection.find()))

In [28]:
if "_id" in df.columns:
    df.drop(columns=["_id"], inplace=True)

In [29]:
df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified